name = "chat-backend"
main = "src/index.js"
compatibility_date = "2023-09-01"

worker_dev = true

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "RoomDurable" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurable"]
